[package]
name = "vnd-ethereum-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", default-features = false, features = ["alloc", "derive"] }

[profile.release]
opt-level = "s"
lto = true

[workspace]
