[target.nanosplus]
runner = "speculos -a=1 --model=nanosp"

[build]
target = "nanosplus"

[env]
# The value of CUSTOM_IO_APDU_BUFFER_SIZE needs to be compatible with the MAX_APDU_DATA_SIZE
# constant, taking into account the overhead for APDU headers
LEDGER_SDK_EXTRA_DEFINES="CUSTOM_IO_APDU_BUFFER_SIZE=600"
HEAP_SIZE = "nanox: 14336, nanosplus: 31744, flex: 26624, stax: 26624, apex_p: 30720"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
