[target.flex]
runner = "speculos -a=22 --model=flex"

[build]
target = "flex"

[env]
LEDGER_SDK_EXTRA_DEFINES="CUSTOM_IO_APDU_BUFFER_SIZE=600 API_LEVEL=22"
HEAP_SIZE = "nanox: 14336, nanosplus: 31744, flex: 26624, stax: 26624, apex_p: 26624"
LEDGER_SDK_PATH = { value = "/root/ledger-secure-sdk", force = true }

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
